[package]
name = "ordo"
version = "0.1.0"
edition = "2021"
authors = ["Sergiy Protsiv <sergiy@protsiv.net>"]
description = "A causal delivery protocol on top of reto"
readme = "README.md"
repository = "https://github.com/fidinda/ordo"
license = "MIT OR Apache-2.0"
keywords = ["networking"]
